Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.linear_model import LogisticRegression

sk_model = LogisticRegression(random_state=0, penalty="none", solver="newton-cg")
_ = sk_model.fit(X_train, y_train)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mInvalidParameterError[0m                     Traceback (most recent call last)
Cell [0;32mIn[11], line 4[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mlinear_model[39;00m [38;5;28;01mimport[39;00m LogisticRegression
[1;32m      3[0m sk_model [38;5;241m=[39m LogisticRegression(random_state[38;5;241m=[39m[38;5;241m0[39m, penalty[38;5;241m=[39m[38;5;124m"[39m[38;5;124mnone[39m[38;5;124m"[39m, solver[38;5;241m=[39m[38;5;124m"[39m[38;5;124mnewton-cg[39m[38;5;124m"[39m)
[0;32m----> 4[0m _ [38;5;241m=[39m [43msk_model[49m[38;5;241;43m.[39;49m[43mfit[49m[43m([49m[43mX_train[49m[43m,[49m[43m [49m[43my_train[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/sklearn/base.py:1344[0m, in [0;36m_fit_context.<locals>.decorator.<locals>.wrapper[0;34m(estimator, *args, **kwargs)[0m
[1;32m   1339[0m partial_fit_and_fitted [38;5;241m=[39m (
[1;32m   1340[0m     fit_method[38;5;241m.[39m[38;5;18m__name__[39m [38;5;241m==[39m [38;5;124m"[39m[38;5;124mpartial_fit[39m[38;5;124m"[39m [38;5;129;01mand[39;00m _is_fitted(estimator)
[1;32m   1341[0m )
[1;32m   1343[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m global_skip_validation [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m partial_fit_and_fitted:
[0;32m-> 1344[0m     [43mestimator[49m[38;5;241;43m.[39;49m[43m_validate_params[49m[43m([49m[43m)[49m
[1;32m   1346[0m [38;5;28;01mwith[39;00m config_context(
[1;32m   1347[0m     skip_parameter_validation[38;5;241m=[39m(
[1;32m   1348[0m         prefer_skip_nested_validation [38;5;129;01mor[39;00m global_skip_validation
[1;32m   1349[0m     )
[1;32m   1350[0m ):
[1;32m   1351[0m     [38;5;28;01mreturn[39;00m fit_method(estimator, [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [0;32m/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/sklearn/base.py:666[0m, in [0;36mBaseEstimator._validate_params[0;34m(self)[0m
[1;32m    658[0m [38;5;28;01mdef[39;00m [38;5;21m_validate_params[39m([38;5;28mself[39m):
[1;32m    659[0m [38;5;250m    [39m[38;5;124;03m"""Validate types and values of constructor parameters[39;00m
[1;32m    660[0m 
[1;32m    661[0m [38;5;124;03m    The expected type and values must be defined in the `_parameter_constraints`[39;00m
[0;32m   (...)[0m
[1;32m    664[0m [38;5;124;03m    accepted constraints.[39;00m
[1;32m    665[0m [38;5;124;03m    """[39;00m
[0;32m--> 666[0m     [43mvalidate_parameter_constraints[49m[43m([49m
[1;32m    667[0m [43m        [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_parameter_constraints[49m[43m,[49m
[1;32m    668[0m [43m        [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mget_params[49m[43m([49m[43mdeep[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m)[49m[43m,[49m
[1;32m    669[0m [43m        [49m[43mcaller_name[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[38;5;18;43m__class__[39;49m[38;5;241;43m.[39;49m[38;5;18;43m__name__[39;49m[43m,[49m
[1;32m    670[0m [43m    [49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/sklearn/utils/_param_validation.py:95[0m, in [0;36mvalidate_parameter_constraints[0;34m(parameter_constraints, params, caller_name)[0m
[1;32m     89[0m [38;5;28;01melse[39;00m:
[1;32m     90[0m     constraints_str [38;5;241m=[39m (
[1;32m     91[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00m[38;5;124m'[39m[38;5;124m, [39m[38;5;124m'[39m[38;5;241m.[39mjoin([[38;5;28mstr[39m(c)[38;5;250m [39m[38;5;28;01mfor[39;00m[38;5;250m [39mc[38;5;250m [39m[38;5;129;01min[39;00m[38;5;250m [39mconstraints[:[38;5;241m-[39m[38;5;241m1[39m]])[38;5;132;01m}[39;00m[38;5;124m or[39m[38;5;124m"[39m
[1;32m     92[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124m [39m[38;5;132;01m{[39;00mconstraints[[38;5;241m-[39m[38;5;241m1[39m][38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m     93[0m     )
[0;32m---> 95[0m [38;5;28;01mraise[39;00m InvalidParameterError(
[1;32m     96[0m     [38;5;124mf[39m[38;5;124m"[39m[38;5;124mThe [39m[38;5;132;01m{[39;00mparam_name[38;5;132;01m!r}[39;00m[38;5;124m parameter of [39m[38;5;132;01m{[39;00mcaller_name[38;5;132;01m}[39;00m[38;5;124m must be[39m[38;5;124m"[39m
[1;32m     97[0m     [38;5;124mf[39m[38;5;124m"[39m[38;5;124m [39m[38;5;132;01m{[39;00mconstraints_str[38;5;132;01m}[39;00m[38;5;124m. Got [39m[38;5;132;01m{[39;00mparam_val[38;5;132;01m!r}[39;00m[38;5;124m instead.[39m[38;5;124m"[39m
[1;32m     98[0m )

[0;31mInvalidParameterError[0m: The 'penalty' parameter of LogisticRegression must be a str among {'l2', 'l1', 'elasticnet'} or None. Got 'none' instead.

